name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  PROJECT_FILE_PATH: .\Sources\vietypekey\win32\vietypekey\vietypekey\vietypekey.vcxproj
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build x86
      run: msbuild -m -target:Rebuild -p:Configuration=Release -p:Platform=x86 ${{env.PROJECT_FILE_PATH}}

    - name: Build x64
      run: msbuild -m -target:Rebuild -p:Configuration=Release -p:Platform=x64 ${{env.PROJECT_FILE_PATH}}

    - name: Upload a Build Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: vietypekey
        path: |
          .\Sources\vietypekey\win32\vietypekey\vietypekey\Release\
          .\Sources\vietypekey\win32\vietypekey\vietypekey\x64\Release\

    outputs:
      subject-name: vietypekey
      subject-digest: ${{steps.upload.outputs.artifact-digest}}

  attest:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{needs.build.outputs.subject-name}}
        subject-digest: sha256:${{needs.build.outputs.subject-digest}}
